name: Proxy Build Trigger
on:
  repository_dispatch:
    types: [public_build_request]

jobs:
  trigger:
    runs-on: ubuntu-latest
    if: github.repository_owner == 'NekodaKohaku'
    steps:
      - name: Trigger Public Build
        uses: peter-evans/workflow-dispatch@v1
        with:
          token: ${{ secrets.PUBLIC_TRIGGER_TOKEN }}
          repository: NekodaKohaku/SlimeNRF-Firmware-CI
          workflow: public_build.yml
          ref: main
          inputs: |
            board: ${{ github.event.client_payload.board }}
            iface: ${{ github.event.client_payload.iface }}
            clk: ${{ github.event.client_payload.clk }}
            sleep: ${{ github.event.client_payload.sleep }}
            sw0: ${{ github.event.client_payload.sw0 }}
            mag: ${{ github.event.client_payload.mag }}
            pinmode: ${{ github.event.client_payload.pinmode }}
            wiring: ${{ github.event.client_payload.wiring }}
            filename: ${{ github.event.client_payload.filename }}
